# Generated by Django 4.0.3 on 2023-10-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
